### ISSUE TITLE
Support for 16bit precision training

### ISSUE THREAD

**Issue by BlockWaving** [sktime/pytorch-forecasting#285]
Thanks for the fantastic implementation... this is really a awesome job.
When testing with "precision=16" set on Trainer, however, an error triggered because of following code:

temporal_fusion_...\sub_modules.py
Line 393:  attn = attn.maskked_fill(mask, -1e9)
RuntimeError:  value cannot be converted to type at::Half without overflow -1e9

Please advise to make it support for 16bit training, what should I do here? changing all -1e9 to -1e4 will make it?

**Comment by jdb78** [comment]
Sounds like a great idea. Do you want to replace the number with -3e4 and write a small test to confirm it works? Would be an amazing PR!

**Comment by BlockWaving** [comment]
Test it, changing to -3e4 disappeared the line 393 error, but later in optim.py:
Line 131:  _= closure()
TypeError: 'NoneType' object is not callable

Looks more places need to be touched.

Tracing to training_loop.py(L719-730), closure is created here:

                       def train_step_and_backward_closure():
                            result = self.training_step_and_backward(
                                split_batch,
                                batch_idx,
                                opt_idx,
                                optimizer,
                                self.trainer.hiddens
                            )
                            return None if result is None else result.loss

                        # optimizer step
                        self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
Somehow 'result' was returned as None.
Or is this also a lightning fix?

**Comment by jdb78** [comment]
Hm. Can you try a different optimizer? Maybe ranger is the issue. Could you give `"adam"` a try?

**Comment by mikcnt** [comment]
Hey @jdb78! I'm currently facing the same issue when trying to train the model with mixed precision (`precision = 16`). The first issue is easily solved by replacing -1e9 with either a smaller number like -3e4 like you advised, or with `- math.inf`, which seems like a better option in my opinion.

As for the second one, I've tried using `"adam"` as optimizer, and it seems to work, so ranger is the issue. Any idea on how to proceed? I can totally work on that!

**Comment by sayanb-playground** [comment]
Hi @jdb78, this issue still persists while trying to train TFT with lightning's native mixed precision mode on the following versions.

```
pytorch-forecasting==0.9.0
pytorch-lightning==1.6.5
torch==1.11.0
```

Any chance of getting it fixed in the upcoming version? Let me know if I can be of any help here. I'd be curious to know if mixed precision training will bring down our TFT runtime.

**Comment by wmoreira-abi** [comment]
Up!
